site_name: Assembly Calculator
repo_url: https://github.com/Lex280498/ReadXML_ASSEMBLY
repo_name: Lex280498/ReadXML_ASSEMBLY
nav:
    - Inicio: index.md
    - Macros:
      - Manejo de Archivos: macros/files.md
      - Propósito General: macros/macros.md
    - Procedimientos: proc.md
    - Analísis: analysis.md
    - Acerda De y Referencias: about.md

theme:
  name: material 
  features:
    - navigation.expand
    - navigation.indexes
    - navigation.tabs

  palette:
    scheme: slate
    primary: red
    accent: deep orange

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

copyright: Por Alex Méndez
